#!/bin/bash
set -e
echo "Call the Quartus11 jtagd for the USB Blaster"
# set env
source ~/config/scripts/quartus9.1.sh

# sudo killall jtagd
sudo /opt/altera/11.0/quartus/bin/jtagd
jtagconfig

exit 0
